default: &default
  adapter: postgresql
  encoding: UTF8
  host: db
  pool: 10
  username: postgres
  password: postgres

development:
  <<: *default
  database: katello_dev

test:
  <<: *default
  database: katello_test

production:
  <<: *default
  database: katello_prod
