db:
  image: postgres:9.2.23-alpine
  ports:
    - "5432:5432"
  restart: always
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: katello_prod

app:
  image: jomitsch/katello-testing-container
  ports:
    - "8080:8080"
  links:
    - db
  environment:
    RAILS_ENV: production
