app:
  image: jomitsch/katello-testing-container
  command: "cd ~/foreman && bundle exec foreman start "
  ports:
    - "3000:3000"
  links:
    - postgres
postgres:
  image: postgres:9.2.23-alpine
  ports:
    - "5432:5432"
