name: Publish Docker Image
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: 0 7 * * 1-5
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jomitsch/katello-testing-container
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
